version: "2"
services:
    jenkins:
        restart: always
        build: .
        volumes:
            - "./data/jenkins_home:/var/jenkins_home"
        environment:
            JENKINS_OPTS: --prefix=/jenkins
        ports:
            - "8080:8080"
